# Generated by Django 4.0.3 on 2022-03-31 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=250, null=True)),
                ('description1', models.TextField(blank=True, max_length=2050, null=True)),
                ('title2', models.CharField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=2050, null=True)),
                ('disclaimer', models.TextField(blank=True, max_length=2050, null=True)),
                ('access_form_url', models.CharField(blank=True, max_length=250, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('future_use1', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use2', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use3', models.TextField(blank=True, max_length=2050, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgLegalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=250)),
                ('value', models.CharField(db_column='Value', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(blank=True, db_column='ORG_CODE', max_length=250, null=True)),
                ('org_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_acronym', models.TextField(blank=True, max_length=1000, null=True)),
                ('founding_year', models.CharField(blank=True, max_length=5, null=True)),
                ('years_active', models.CharField(blank=True, max_length=5, null=True)),
                ('refugee_zone', models.CharField(blank=True, max_length=250, null=True)),
                ('org_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_activities', models.TextField(blank=True, max_length=1500, null=True)),
                ('org_targetgroup', models.CharField(blank=True, max_length=250, null=True)),
                ('org_primarycontact', models.CharField(blank=True, max_length=250, null=True)),
                ('org_email', models.CharField(blank=True, max_length=250, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('org_website', models.CharField(blank=True, max_length=250, null=True)),
                ('org_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('org_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('org_logo', models.TextField(blank=True, max_length=1250, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_role', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_legaltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_legaltype', to='home.orglegaltype')),
                ('org_primarytechnicalarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_thematic_area', to='home.thematicarea')),
                ('org_secondarytechnicalarea1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_thematic_area', to='home.thematicarea')),
                ('org_secondarytechnicalarea2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_thematic_area', to='home.thematicarea')),
                ('org_targetdemographic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_targetdemographic', to='home.targetdemographic')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_type', to='home.orgtype')),
                ('refugee_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='home.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_acronym', models.TextField(blank=True, max_length=1000, null=True)),
                ('founding_year', models.CharField(blank=True, max_length=5, null=True)),
                ('years_active', models.CharField(blank=True, max_length=5, null=True)),
                ('refugee_zone', models.CharField(blank=True, max_length=250, null=True)),
                ('org_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('org_activities', models.TextField(blank=True, max_length=1500, null=True)),
                ('org_targetgroup', models.CharField(blank=True, max_length=250, null=True)),
                ('org_primarycontact', models.CharField(blank=True, max_length=250, null=True)),
                ('org_email', models.CharField(blank=True, max_length=250, null=True)),
                ('org_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('org_website', models.CharField(blank=True, max_length=250, null=True)),
                ('org_facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('org_twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('org_logo', models.TextField(blank=True, max_length=1250, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_role', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_legaltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_org_legaltype', to='home.orglegaltype')),
                ('org_primarytechnicalarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_primary_thematic_area', to='home.thematicarea')),
                ('org_secondarytechnicalarea1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_secondary_thematic_area', to='home.thematicarea')),
                ('org_secondarytechnicalarea2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_third_thematic_area', to='home.thematicarea')),
                ('org_targetdemographic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_org_targetdemographic', to='home.targetdemographic')),
                ('org_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_org_type', to='home.orgtype')),
                ('refugee_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd_settlement', to='home.settlement')),
            ],
        ),
    ]
