# Generated by Django 4.0.3 on 2022-04-17 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementOrgAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zones', models.TextField(blank=True, max_length=1000, null=True)),
                ('operation_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('num_of_staffs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_settlement', to='home.cleandata')),
                ('primary_thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_primary_thematic_area', to='home.thematicarea')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_org', to='home.settlement')),
            ],
        ),
    ]
