# Generated by Django 4.0.3 on 2022-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_settlementorgassociation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleandata',
            old_name='refugee_zone',
            new_name='respondent_email_address',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_activities',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_offices',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_primarytechnicalarea',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea1',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='org_secondarytechnicalarea2',
        ),
        migrations.RemoveField(
            model_name='cleandata',
            name='refugee_settlement',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='org_primary_technical_area_focus',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='other_actors_in_settlement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='respondent_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='settlement_operation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_legaltype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='settlementorgassociation',
            name='primary_thematic_area',
        ),
        migrations.AddField(
            model_name='settlementorgassociation',
            name='primary_thematic_area',
            field=models.ManyToManyField(related_name='settlement_primary_thematic_area', to='home.thematicarea'),
        ),
    ]
