# Generated by Django 4.0.3 on 2022-04-19 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_refugee_zone_cleandata_respondent_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dump',
            old_name='org_offices',
            new_name='operation_offices',
        ),
        migrations.RenameField(
            model_name='dump',
            old_name='refugee_zone',
            new_name='respondent_email_address',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_activities',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_code',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_primarytechnicalarea',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_secondarytechnicalarea1',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='org_secondarytechnicalarea2',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='refugee_settlement',
        ),
        migrations.AddField(
            model_name='dump',
            name='num_of_staffs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_primary_technical_area_focus',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='other_actors_in_settlement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='primary_thematic_area',
            field=models.ManyToManyField(related_name='d_settlement_primary_thematic_area', to='home.thematicarea'),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='respondent_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_settlement_org', to='home.settlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='zones',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='other_actors_in_settlement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='settlement_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_legaltype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_targetdemographic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_org_targetdemographic', to='home.targetdemographic'),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_org_type', to='home.orgtype'),
        ),
        migrations.CreateModel(
            name='AlternativeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo_url', models.CharField(blank=True, max_length=700, null=True)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_type_logo', to='home.orgtype')),
            ],
        ),
    ]
