# Generated by Django 4.0.3 on 2022-04-19 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_org_offices_dump_operation_offices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_settlement_org', to='home.settlement'),
        ),
    ]
