# Generated by Django 4.0.3 on 2022-04-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dump_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDetailsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('future_use1', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use2', models.CharField(blank=True, max_length=250, null=True)),
                ('future_use3', models.TextField(blank=True, max_length=2050, null=True)),
            ],
        ),
    ]
