# Generated by Django 4.0.3 on 2022-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_orgdetailspagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='map_description',
            field=models.TextField(blank=True, max_length=1050, null=True),
        ),
    ]
