# Generated by Django 4.0.3 on 2022-04-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_landingpagecontent_map_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleandata',
            name='org_targetdemographic',
        ),
        migrations.AddField(
            model_name='cleandata',
            name='org_targetdemographic',
            field=models.ManyToManyField(related_name='cd_org_targetdemographic', to='home.targetdemographic'),
        ),
    ]
