# Generated by Django 4.0.3 on 2022-04-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_cleandata_org_targetdemographic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cleandata',
            name='org_primary_technical_area_focus',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='settlementorgassociation',
            name='primary_thematic_area',
            field=models.ManyToManyField(blank=True, null=True, related_name='settlement_primary_thematic_area', to='home.thematicarea'),
        ),
    ]
