# Generated by Django 4.0.3 on 2022-05-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cleandata_logo_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgtype',
            old_name='exclude_from_filter',
            new_name='is_other',
        ),
        migrations.RenameField(
            model_name='targetdemographic',
            old_name='exclude_from_filter',
            new_name='is_other',
        ),
        migrations.RenameField(
            model_name='thematicarea',
            old_name='exclude_from_filter',
            new_name='is_other',
        ),
    ]
