# Generated by Django 4.0.3 on 2022-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_is_other_orgtype_exclude_from_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleandata',
            name='associated_settlements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='associated_thematic_areas',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='total_num_of_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
