# Generated by Django 4.0.3 on 2022-05-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_cleandata_options_alter_dump_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleandata',
            name='org_targetdemographic',
            field=models.ManyToManyField(blank=True, null=True, related_name='cd_org_targetdemographic', to='home.targetdemographic'),
        ),
    ]
