# Generated by Django 4.0.3 on 2022-05-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_cleandata_org_targetdemographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativelogo',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cleandata',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orgdetailspagecontent',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orglegaltype',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orgtype',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlementorgassociation',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='targetdemographic',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thematicarea',
            name='upsrt_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='settlementorgassociation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
