# Generated by Django 4.0.3 on 2022-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alternativelogo_upsrt_dttm_cleandata_upsrt_dttm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dump',
            old_name='num_of_staffs',
            new_name='total_num_of_staff',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='operation_offices',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='primary_thematic_area',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='settlement',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='zones',
        ),
        migrations.AddField(
            model_name='dump',
            name='associated_settlements',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='associated_thematic_areas',
            field=models.TextField(blank=True, max_length=1250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_legaltype_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_targetdemographic_other',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_targetgroup_other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='org_type_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_4',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='settlement_5',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='uuid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_legaltype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_primary_technical_area_focus',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_targetdemographic',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='org_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
