# Generated by Django 4.0.3 on 2022-06-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_dump_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dump',
            name='settlement_2',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='settlement_3',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='settlement_4',
        ),
        migrations.RemoveField(
            model_name='dump',
            name='settlement_5',
        ),
        migrations.CreateModel(
            name='DumpSettlements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement', models.CharField(blank=True, max_length=120, null=True)),
                ('primary_thematic_area', models.CharField(blank=True, max_length=250, null=True)),
                ('zones', models.CharField(blank=True, max_length=250, null=True)),
                ('operation_offices', models.TextField(blank=True, max_length=1000, null=True)),
                ('num_of_staffs', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upsrt_dttm', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_settlement', to='home.dump')),
            ],
        ),
    ]
