# Generated by Django 4.0.3 on 2022-06-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_dump_settlement_2_remove_dump_settlement_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dump',
            name='settlement_1',
        ),
    ]
